# Natural Language Processing, Homework 1
 Dr. Sharon Yalov-Handzel

You can submit the homework as *.py or *.ipynb file.  
Answers to theoretical questions can be written in a separate WORD document.

Submitted by  
Michael Berger,  
Barak Samuni


  ## 1. Setup a python environment on your computer (Pycharm / google colab).

In [1]:
import pandas as pd


  ## 2. Install the following libraries: pytorch, NLTK, spaCy

In [4]:
#conda install -y pytorch NLTK spaCy


  ## 3. Write a program that loads the file spam.csv (source: KAGGLE)

In [6]:
spam = pd.read_csv("data/spam.csv",encoding='Windows-1252')


  ## 4. Compute simple statistics on the data:   
  number of SMS message, number of spams,
total word count, averaged number of words per message, 5 most frequent words in
the file, number of rare words (appear only once in the file).


  ## 5. Perform tokenization twice:

  ### a) by using NLTK library

  
Barak

first let's view the data:

In [7]:
spam.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

It seems that v1 contains the classification of the message and v2 contains the message itself. so we would like to tokenize v2:

In [8]:
# Tokenization using NLTK
import nltk
from nltk.tokenize import word_tokenize

# Ensure the NLTK tokenizer required resources are downloaded
nltk.download('punkt')

# Tokenize the 'v2' column from the DataFrame
spam['tokens_nltk'] = spam['v2'].apply(word_tokenize)

# Display tokenized data
spam[['v2', 'tokens_nltk']].head()

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\barak\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

,v2,tokens_nltk
0,"Go until jurong point, crazy.. Available only ...","[Go, until, jurong, point, ,, crazy, .., Avail..."
1,Ok lar... Joking wif u oni...,"[Ok, lar, ..., Joking, wif, u, oni, ...]"
2,Free entry in 2 a wkly comp to win FA Cup fina...,"[Free, entry, in, 2, a, wkly, comp, to, win, F..."
3,U dun say so early hor... U c already then say...,"[U, dun, say, so, early, hor, ..., U, c, alrea..."
4,"Nah I don't think he goes to usf, he lives aro...","[Nah, I, do, n't, think, he, goes, to, usf, ,,..."

  ### b) and by Spacy library. 

Michael

  ### c) Write what is the difference between the results.


  ## 6. Perform lemmatization
  by NLTK and
  barak

In [10]:
# Perform lemmatization using NLTK
from nltk.stem import WordNetLemmatizer

# Ensure the required resources for lemmatization are downloaded
nltk.download('wordnet')
nltk.download('omw-1.4')

# Initialize lemmatizer
lemmatizer = WordNetLemmatizer()

# Define a function to lemmatize tokens
def lemmatize_tokens(tokens):
    return [lemmatizer.lemmatize(token) for token in tokens]

# Apply lemmatization to the 'tokens' column
spam['lemmatized_tokens_nltk'] = spam['tokens_nltk'].apply(lemmatize_tokens)

# Display lemmatized data
spam[['v2', 'tokens_nltk', 'lemmatized_tokens_nltk']].head()

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\barak\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\barak\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

,v2,tokens_nltk,lemmatized_tokens_nltk
0,"Go until jurong point, crazy.. Available only ...","[Go, until, jurong, point, ,, crazy, .., Avail...","[Go, until, jurong, point, ,, crazy, .., Avail..."
1,Ok lar... Joking wif u oni...,"[Ok, lar, ..., Joking, wif, u, oni, ...]","[Ok, lar, ..., Joking, wif, u, oni, ...]"
2,Free entry in 2 a wkly comp to win FA Cup fina...,"[Free, entry, in, 2, a, wkly, comp, to, win, F...","[Free, entry, in, 2, a, wkly, comp, to, win, F..."
3,U dun say so early hor... U c already then say...,"[U, dun, say, so, early, hor, ..., U, c, alrea...","[U, dun, say, so, early, hor, ..., U, c, alrea..."
4,"Nah I don't think he goes to usf, he lives aro...","[Nah, I, do, n't, think, he, goes, to, usf, ,,...","[Nah, I, do, n't, think, he, go, to, usf, ,, h..."

  by Spacy libraries. 

Michael

  Write what is the difference between the results.


  ## 7. Perform stemming 
  by NLTK twice on both results of (6). Write what is the difference between the results.

Barak


  ## 8. Identify a spam message where its removal from the spam.csv dataset would:


  ### a)Reduce the total number of stemmed tokens
  
BArak


  ### b)Maintain the exact same number of lemmatized tokens
Michael

If no such message exists, provide a detailed explanation of why this scenario is
impossible or improbable.



  ## 9. Identify a spam message where its removal from the spam.csv dataset would:


  ### a)Reduce the total number of lemmatized tokens
  
Barak


  ### b)Maintain the exact same number of stemmed tokens

  Michael
If no such message exists, provide a detailed explanation of why this scenario is
impossible or improbable.



  ## 10. Compare the results of  
  NLTK before and after tokenization, lemmatization and stemming

  BArak


  ## 11. Compare the results of 
  Spacy before and after tokenization and lemmatization.

MIchael


  ## 12. Install the library BeautifulSoup


  ## 13. Choose any url page. 
  You can choose a page of yourself in a social media (e.g., facebook, Instagram, Linkdin, Twitter), or anything else


  ## 14. Perform data scrapping of this url. 
  You can learn how to do it from the following links:  
https://www.edureka.co/blog/web-scraping-with-python/  
https://zindi.africa/learn/a-beginners-guide-to-scraping-data-from-social-media  
or, ask CHATGPT to program it for you.  

Michael


  ## 15. Perform steps 5-11 on the text achieved in (14).


  ## 16. Download one of your whatsapp chats into *.txt file 
  (at least 50 messages in Hebrew).

  Barack


  ## 17. Repeat steps 5-11 on the text file achieved in (16)