# Review of the available datasets

In [ ]:
import pandas as pd
import os
import jq

import warnings

from datasets import load_dataset
from datasets import load_dataset_builder

# a little trick to allow imports from local modules when running in Jupyter
import sys
from pathlib import Path
__file__ = os.path.abspath('')
sys.path.append(str(Path(__file__).absolute().parent))

In [ ]:



from MyTools.Zotero_connect import zot 

from MyTools import DataIO, Viz

In [12]:
zot

## Connect to Zotero

In [13]:
zot.collections()

ConnectError: [Errno 111] Connection refused

In [8]:
# Get a list of all your top-level collections
collections = zot.collections()

# Find the key for a specific collection by name
collection_key = None
for col in collections:
    if col['data']['name'] == "Reviewed":
        collection_key = col['data']['key']
        break

if collection_key:
    print(f"Found key for 'Datasets review': {collection_key}")
else:
    print("Collection not found. Please check the name.")

Found key for 'Datasets review': T8YELS8J

In [9]:
collection_key

'T8YELS8J'

In [12]:
#q="",  tag="", limit=10
articles = zot.items(qmode="everything", itemType="dataset", 
                     collection="T8YELS8J", fields="citationKey")
print(len(articles))

18

In [13]:
articles = zot.collection_items("T8YELS8J", qmode="everything", itemType="dataset", 
                      fields="citationKey")

print(len(articles))

6

In [ ]:
DataIO.jsave(articles, "articles.json")

In [15]:
jq_query = "map({key: .data.key, title: .data.title, \
                 extra: .data.extra, itemType: .data.itemType, \
                 url: .data.url, repository: .data.repository })"
result = jq.compile(jq_query).input(articles)
result = result.all()[0]
result

[{'key': 'A5NWSHSV',
  'title': 'yhua219/EduRABSA_ASQE · Datasets at Hugging Face',
  'extra': 'Citation Key: Yhua219EduRABSA_ASQEDatasets2025',
  'itemType': 'dataset',
  'url': 'https://huggingface.co/datasets/yhua219/EduRABSA_ASQE',
  'repository': 'huggingface'},
 {'key': 'M84HPF9U',
  'title': 'Welcome to Coursera Dataset',
  'extra': 'Citation Key: WelcomeCourseraDataset',
  'itemType': 'dataset',
  'url': 'https://pageperso.lis-lab.fr/ismail.badache/Reviews_ExtracTerms%20HTML/',
  'repository': 'lis-lab.fr'},
 {'key': 'YNX7QNIU',
  'title': 'Course Reviews University of Waterloo',
  'extra': 'Citation Key: CourseReviewsUniversity',
  'itemType': 'dataset',
  'url': 'https://www.kaggle.com/datasets/anthonysusevski/course-reviews-university-of-waterloo',
  'repository': 'kaggle'},
 {'key': 'Z9Z2GX4A',
  'title': 'Course Reviews on Coursera',
  'extra': 'Citation Key: CourseReviewsCoursera',
  'itemType': 'dataset',
  'url': 'https://www.kaggle.com/datasets/imuhammad/course-reviews-on-coursera',
  'repository': 'kaggle'},
 {'key': '878DC5JH',
  'title': 'Udemy Course Review',
  'extra': 'Citation Key: UdemyCourseReview',
  'itemType': 'dataset',
  'url': 'https://www.kaggle.com/datasets/sabrisangjaya/udemy-course-review',
  'repository': 'kaggle'},
 {'key': 'EJWCRLAM',
  'title': 'chillies/course-review-multilabel-sentiment-analysis · Datasets at Hugging Face',
  'extra': 'Citation Key: ChilliesCoursereviews2024',
  'itemType': 'dataset',
  'url': 'https://huggingface.co/datasets/chillies/course-review-multilabel-sentiment-analysis',
  'repository': 'huggingface'}]

### Get Articles

In [16]:
dss = pd.DataFrame(result)
dss["citekey"] = dss.extra.apply(lambda r: r.split("Citation Key: ")[1])
dss.drop("extra",axis=1, inplace=True)
dss.sort_values("repository")

,key,title,itemType,url,repository,citekey
0,A5NWSHSV,yhua219/EduRABSA_ASQE · Datasets at Hugging Face,dataset,https://huggingface.co/datasets/yhua219/EduRAB...,huggingface,Yhua219EduRABSA_ASQEDatasets2025
5,EJWCRLAM,chillies/course-review-multilabel-sentiment-an...,dataset,https://huggingface.co/datasets/chillies/cours...,huggingface,ChilliesCoursereviews2024
2,YNX7QNIU,Course Reviews University of Waterloo,dataset,https://www.kaggle.com/datasets/anthonysusevsk...,kaggle,CourseReviewsUniversity
3,Z9Z2GX4A,Course Reviews on Coursera,dataset,https://www.kaggle.com/datasets/imuhammad/cour...,kaggle,CourseReviewsCoursera
4,878DC5JH,Udemy Course Review,dataset,https://www.kaggle.com/datasets/sabrisangjaya/...,kaggle,UdemyCourseReview
1,M84HPF9U,Welcome to Coursera Dataset,dataset,https://pageperso.lis-lab.fr/ismail.badache/Re...,lis-lab.fr,WelcomeCourseraDataset

## Read the Datasets

In [20]:
#read_any(pth)

## Download datasets

In [ ]:




need_preprocess = {"Yhua219EduRABSA_ASQEDatasets2025": lambda d: EXPLOSON(d, 'output')}

In [ ]:

tst = DataIO.read_any(fl)
tst

NameError: name 'fl' is not defined

In [ ]:
tst = DataIO.EXPLOSON(tst, 'labels')

NameError: name 'tst' is not defined

In [26]:
os.path.dirname(end)
#  (end)

NameError: name 'end' is not defined

In [28]:
dss

,key,title,itemType,url,repository,citekey
0,A5NWSHSV,yhua219/EduRABSA_ASQE · Datasets at Hugging Face,dataset,https://huggingface.co/datasets/yhua219/EduRAB...,huggingface,Yhua219EduRABSA_ASQEDatasets2025
1,M84HPF9U,Welcome to Coursera Dataset,dataset,https://pageperso.lis-lab.fr/ismail.badache/Re...,lis-lab.fr,WelcomeCourseraDataset
2,YNX7QNIU,Course Reviews University of Waterloo,dataset,https://www.kaggle.com/datasets/anthonysusevsk...,kaggle,CourseReviewsUniversity
3,Z9Z2GX4A,Course Reviews on Coursera,dataset,https://www.kaggle.com/datasets/imuhammad/cour...,kaggle,CourseReviewsCoursera
4,878DC5JH,Udemy Course Review,dataset,https://www.kaggle.com/datasets/sabrisangjaya/...,kaggle,UdemyCourseReview
5,EJWCRLAM,chillies/course-review-multilabel-sentiment-an...,dataset,https://huggingface.co/datasets/chillies/cours...,huggingface,ChilliesCoursereviews2024

In [29]:
itm = dss.loc[1]
itm

key                                                    M84HPF9U
title                               Welcome to Coursera Dataset
itemType                                                dataset
url           https://pageperso.lis-lab.fr/ismail.badache/Re...
repository                                           lis-lab.fr
citekey                                  WelcomeCourseraDataset
Name: 1, dtype: object

In [30]:
base_url

NameError: name 'base_url' is not defined

In [72]:
outputs_root = "data"
#outputs_root ="/home/michael/Dropbox/Studies/M.Sc./Capstone/Datasets"

In [ ]:
dfs = DataIO.download(itm)

In [32]:
dfs.keys()

dict_keys(['Frequencies Stats', 'Emotional & Reaction Terms', 'Aspect Terms Sentiment M1 NLTK', 'Aspect Terms Sentiment M2 Learn NB', 'Emoticones', 'Aspect Terms Sentiment_Cont M1 NLTK', 'Aspect Terms Sentiment_Cont M2 Learn NB'])

## Generate summaries

In [36]:
df = dfs['train']

KeyError: 'train'

In [ ]:
hists_data = df.apply(lambda row: Viz.create_png_histogram(row), axis=0)

NameError: name 'df' is not defined

In [38]:
hists_data

NameError: name 'hists_data' is not defined

## Pipeline

In [44]:
summ = summs['test']
summ

NameError: name 'summs' is not defined

In [ ]:

# This pipeline writes summaries of each table as headers under item's md file

def pipeline(item, force = False):
    #print(item.citekey)
    
    #folder = outputs_root + "/" + item.citekey
    # if os.path.isdir(folder) :
    #     print("skipping existing item", folder, "from",  item.repository.lower() )
    #     return # None, folder
    
    dfs = DataIO.download(item)

    itemname = item.citekey
    document = f"Title: {item.title}\n\n" +\
               f"URL: [{item.url}]({item.url})\n\n" +\
               f"Repository: {item.repository}\n\n"
    imgs = {}
    summs = {}
    for dfname, df in dfs.items():
        dfname = os.path.splitext(dfname)[0]

        docname = os.path.join(outputs_root , itemname + '.md')

        if os.path.exists(docname) and not force:
            print (f"Skipping summarization - already exists: '{docname}'")
            continue

        try:
            summ = Viz.summary(df, hist_fmt='png')
        except Exception as e:
            summ = pd.DataFrame([["oops",b"oobs","Error during summarization", str(e)]], columns=["Column", "Hist", "Error", "Message"])
            warnings.warn(f"Error summarizing {dfname}: {e}")
        summs[dfname] = summ
        

        md, assets = DataIO.to_md(summ, itemname,dfname)
        document += f"## Table: {dfname}\n\n"
        document += md + "\n\n"
        imgs.update(assets)

    DataIO.md_save(outputs_root, itemname, document, imgs)
    print("saved", itemname)

    return dfs, summs

In [47]:
dss

,key,title,itemType,url,repository,citekey
0,A5NWSHSV,yhua219/EduRABSA_ASQE · Datasets at Hugging Face,dataset,https://huggingface.co/datasets/yhua219/EduRAB...,huggingface,Yhua219EduRABSA_ASQEDatasets2025
1,M84HPF9U,Welcome to Coursera Dataset,dataset,https://pageperso.lis-lab.fr/ismail.badache/Re...,lis-lab.fr,WelcomeCourseraDataset
2,YNX7QNIU,Course Reviews University of Waterloo,dataset,https://www.kaggle.com/datasets/anthonysusevsk...,kaggle,CourseReviewsUniversity
3,Z9Z2GX4A,Course Reviews on Coursera,dataset,https://www.kaggle.com/datasets/imuhammad/cour...,kaggle,CourseReviewsCoursera
4,878DC5JH,Udemy Course Review,dataset,https://www.kaggle.com/datasets/sabrisangjaya/...,kaggle,UdemyCourseReview
5,EJWCRLAM,chillies/course-review-multilabel-sentiment-an...,dataset,https://huggingface.co/datasets/chillies/cours...,huggingface,ChilliesCoursereviews2024

In [48]:
itm = dss.loc[1]
itm

key                                                    M84HPF9U
title                               Welcome to Coursera Dataset
itemType                                                dataset
url           https://pageperso.lis-lab.fr/ismail.badache/Re...
repository                                           lis-lab.fr
citekey                                  WelcomeCourseraDataset
Name: 1, dtype: object

In [ ]:

dfs, summs =  pipeline(itm, True)

downloading https://pageperso.lis-lab.fr/ismail.badache/Reviews_ExtracTerms%20HTML/
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Reviews_ExtracTerms%20HTML.html.
failed to collect subtable No objects to concatenate
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Frequencies Stats/Frequencies_Terms_RatingALL.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emotional & Reaction Terms/Reviews_ExtracTerm_Amazing.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emotional & Reaction Terms/Reviews_ExtracTerm_Awesome.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emotional & Reaction Terms/Reviews_ExtracTerm_Bad.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emotional & Reaction Terms/Reviews_ExtracTerm_Basic.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emotional & Reaction Terms/Reviews_ExtracTerm_Best.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emotional & Reaction Terms/Reviews_ExtracTerm_Boring.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emotional & Reaction Terms/Reviews_ExtracTerm_Clear.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emotional & Reaction Terms/Reviews_ExtracTerm_Cool.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emotional & Reaction Terms/Reviews_ExtracTerm_Difficult.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emotional & Reaction Terms/Reviews_ExtracTerm_Disappoint.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emotional & Reaction Terms/Reviews_ExtracTerm_Easy.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emotional & Reaction Terms/Reviews_ExtracTerm_Enjoy.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emotional & Reaction Terms/Reviews_ExtracTerm_Excellent.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emotional & Reaction Terms/Reviews_ExtracTerm_Fantastic.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emotional & Reaction Terms/Reviews_ExtracTerm_Good.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emotional & Reaction Terms/Reviews_ExtracTerm_Great.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emotional & Reaction Terms/Reviews_ExtracTerm_Hard.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emotional & Reaction Terms/Reviews_ExtracTerm_Hate.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emotional & Reaction Terms/Reviews_ExtracTerm_Helpful.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emotional & Reaction Terms/Reviews_ExtracTerm_Interesting.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emotional & Reaction Terms/Reviews_ExtracTerm_Like.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emotional & Reaction Terms/Reviews_ExtracTerm_Love.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emotional & Reaction Terms/Reviews_ExtracTerm_Nice.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emotional & Reaction Terms/Reviews_ExtracTerm_Poor.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emotional & Reaction Terms/Reviews_ExtracTerm_Recommend.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emotional & Reaction Terms/Reviews_ExtracTerm_Thank.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emotional & Reaction Terms/Reviews_ExtracTerm_Understand.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emotional & Reaction Terms/Reviews_ExtracTerm_Useful.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emotional & Reaction Terms/Reviews_ExtracTerm_Well.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emotional & Reaction Terms/Reviews_ExtracTerm_Wonderful.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M1 NLTK/Reviews_ExtracTerm_C_Sent_Assignment.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M1 NLTK/Reviews_ExtracTerm_C_Sent_Content.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M1 NLTK/Reviews_ExtracTerm_C_Sent_Course.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M1 NLTK/Reviews_ExtracTerm_C_Sent_Design.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M1 NLTK/Reviews_ExtracTerm_C_Sent_Exercise.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M1 NLTK/Reviews_ExtracTerm_C_Sent_Information.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M1 NLTK/Reviews_ExtracTerm_C_Sent_Instructor.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M1 NLTK/Reviews_ExtracTerm_C_Sent_Knowledge.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M1 NLTK/Reviews_ExtracTerm_C_Sent_Lecture.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M1 NLTK/Reviews_ExtracTerm_C_Sent_Lecturer.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M1 NLTK/Reviews_ExtracTerm_C_Sent_Lesson.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M1 NLTK/Reviews_ExtracTerm_C_Sent_Material.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M1 NLTK/Reviews_ExtracTerm_C_Sent_Method.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M1 NLTK/Reviews_ExtracTerm_C_Sent_Presentation.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M1 NLTK/Reviews_ExtracTerm_C_Sent_Professor.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M1 NLTK/Reviews_ExtracTerm_C_Sent_Quality.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M1 NLTK/Reviews_ExtracTerm_C_Sent_Question.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M1 NLTK/Reviews_ExtracTerm_C_Sent_Quizz.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M1 NLTK/Reviews_ExtracTerm_C_Sent_Slide.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M1 NLTK/Reviews_ExtracTerm_C_Sent_Speaker.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M1 NLTK/Reviews_ExtracTerm_C_Sent_Student.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M1 NLTK/Reviews_ExtracTerm_C_Sent_Teach.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M1 NLTK/Reviews_ExtracTerm_C_Sent_Teacher.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M1 NLTK/Reviews_ExtracTerm_C_Sent_Time.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M1 NLTK/Reviews_ExtracTerm_C_Sent_Topic.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M1 NLTK/Reviews_ExtracTerm_C_Sent_Video.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M2 Learn NB/Reviews_ExtracTerm_C_Sent_Assignment.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M2 Learn NB/Reviews_ExtracTerm_C_Sent_Content.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M2 Learn NB/Reviews_ExtracTerm_C_Sent_Course.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M2 Learn NB/Reviews_ExtracTerm_C_Sent_Design.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M2 Learn NB/Reviews_ExtracTerm_C_Sent_Exercise.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M2 Learn NB/Reviews_ExtracTerm_C_Sent_Information.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M2 Learn NB/Reviews_ExtracTerm_C_Sent_Instructor.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M2 Learn NB/Reviews_ExtracTerm_C_Sent_Knowledge.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M2 Learn NB/Reviews_ExtracTerm_C_Sent_Lecture.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M2 Learn NB/Reviews_ExtracTerm_C_Sent_Lecturer.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M2 Learn NB/Reviews_ExtracTerm_C_Sent_Lesson.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M2 Learn NB/Reviews_ExtracTerm_C_Sent_Material.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M2 Learn NB/Reviews_ExtracTerm_C_Sent_Method.html.
Failed to retrieve https://pageperso.lis-lab.fr/ismail.badache/Reviews_ExtracTerms%20HTML/Aspect%20Terms%20Sentiment%20M2%20Learn%20NB/Reviews_ExtracTerm_C_Sent_Presentation.html and no alternative available.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M2 Learn NB/Reviews_ExtracTerm_C_Sent_Professor.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M2 Learn NB/Reviews_ExtracTerm_C_Sent_Quality.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M2 Learn NB/Reviews_ExtracTerm_C_Sent_Question.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M2 Learn NB/Reviews_ExtracTerm_C_Sent_Quizz.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M2 Learn NB/Reviews_ExtracTerm_C_Sent_Slide.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M2 Learn NB/Reviews_ExtracTerm_C_Sent_Speaker.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M2 Learn NB/Reviews_ExtracTerm_C_Sent_Student.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M2 Learn NB/Reviews_ExtracTerm_C_Sent_Teach.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M2 Learn NB/Reviews_ExtracTerm_C_Sent_Teacher.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M2 Learn NB/Reviews_ExtracTerm_C_Sent_Time.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M2 Learn NB/Reviews_ExtracTerm_C_Sent_Topic.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M2 Learn NB/Reviews_ExtracTerm_C_Sent_Video.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emoticones/Reviews_ExtracTerm_EmotHaha.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emoticones/Reviews_ExtracTerm_EmotLove.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emoticones/Reviews_ExtracTerm_EmotSad.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emoticones/Reviews_ExtracTerm_EmotSmile.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M1 NLTK/Sent_Cont_Assignment.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M1 NLTK/Sent_Cont_Content.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M1 NLTK/Sent_Cont_Course.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M1 NLTK/Sent_Cont_Design.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M1 NLTK/Sent_Cont_Exercise.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M1 NLTK/Sent_Cont_Information.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M1 NLTK/Sent_Cont_Instructor.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M1 NLTK/Sent_Cont_Knowledge.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M1 NLTK/Sent_Cont_Lecture.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M1 NLTK/Sent_Cont_Lecturer.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M1 NLTK/Sent_Cont_Lesson.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M1 NLTK/Sent_Cont_Material.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M1 NLTK/Sent_Cont_Method.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M1 NLTK/Sent_Cont_Presentation.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M1 NLTK/Sent_Cont_Professor.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M1 NLTK/Sent_Cont_Quality.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M1 NLTK/Sent_Cont_Question.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M1 NLTK/Sent_Cont_Quizz.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M1 NLTK/Sent_Cont_Slide.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M1 NLTK/Sent_Cont_Speaker.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M1 NLTK/Sent_Cont_Student.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M1 NLTK/Sent_Cont_Teach.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M1 NLTK/Sent_Cont_Teacher.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M1 NLTK/Sent_Cont_Time.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M1 NLTK/Sent_Cont_Topic.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M1 NLTK/Sent_Cont_Video.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M2 Learn NB/Sent_Cont_Assignment.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M2 Learn NB/Sent_Cont_Content.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M2 Learn NB/Sent_Cont_Course.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M2 Learn NB/Sent_Cont_Design.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M2 Learn NB/Sent_Cont_Exercise.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M2 Learn NB/Sent_Cont_Information.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M2 Learn NB/Sent_Cont_Instructor.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M2 Learn NB/Sent_Cont_Knowledge.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M2 Learn NB/Sent_Cont_Lecture.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M2 Learn NB/Sent_Cont_Lecturer.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M2 Learn NB/Sent_Cont_Lesson.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M2 Learn NB/Sent_Cont_Material.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M2 Learn NB/Sent_Cont_Method.html.

In [59]:
summs.keys()

dict_keys(['Frequencies Stats', 'Emotional & Reaction Terms', 'Aspect Terms Sentiment M1 NLTK', 'Aspect Terms Sentiment M2 Learn NB', 'Emoticones', 'Aspect Terms Sentiment_Cont M1 NLTK', 'Aspect Terms Sentiment_Cont M2 Learn NB'])

In [60]:
summs['train']

KeyError: 'train'

In [61]:
summ = summs['train']
summ.columns.to_list()

KeyError: 'train'

In [62]:
[10] * 5 + [None] + [40,40]

[10, 10, 10, 10, 10, None, 40, 40]

## Run Pipeline for all items

In [63]:
outputs_root

'data'

In [64]:

DFs = {}
SUMMARIEs = {}

for i, itm in dss.iterrows():
    
    df, summ = pipeline(itm, True)
    DFs[itm.citekey] = df
    SUMMARIEs[itm.citekey] = summ

print("all done")

downloading https://huggingface.co/datasets/yhua219/EduRABSA_ASQE

README.md: 0.00B [00:00, ?B/s]

Generating train split:   0%|          | 0/4000 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/2500 [00:00<?, ? examples/s]

downloaded to /home/michael/.cache/huggingface/datasets/yhua219___edu_rabsa_asqe/default/0.0.0/bdeeac29ef0fca2fc1f84064217d1ee52748760f
files: ['dataset_info.json', 'edu_rabsa_asqe-test.arrow', 'edu_rabsa_asqe-train.arrow']
saved Yhua219EduRABSA_ASQEDatasets2025
downloading https://pageperso.lis-lab.fr/ismail.badache/Reviews_ExtracTerms%20HTML/
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Reviews_ExtracTerms%20HTML.html.
failed to collect subtable No objects to concatenate
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Frequencies Stats/Frequencies_Terms_RatingALL.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emotional & Reaction Terms/Reviews_ExtracTerm_Amazing.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emotional & Reaction Terms/Reviews_ExtracTerm_Awesome.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emotional & Reaction Terms/Reviews_ExtracTerm_Bad.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emotional & Reaction Terms/Reviews_ExtracTerm_Basic.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emotional & Reaction Terms/Reviews_ExtracTerm_Best.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emotional & Reaction Terms/Reviews_ExtracTerm_Boring.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emotional & Reaction Terms/Reviews_ExtracTerm_Clear.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emotional & Reaction Terms/Reviews_ExtracTerm_Cool.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emotional & Reaction Terms/Reviews_ExtracTerm_Difficult.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emotional & Reaction Terms/Reviews_ExtracTerm_Disappoint.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emotional & Reaction Terms/Reviews_ExtracTerm_Easy.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emotional & Reaction Terms/Reviews_ExtracTerm_Enjoy.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emotional & Reaction Terms/Reviews_ExtracTerm_Excellent.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emotional & Reaction Terms/Reviews_ExtracTerm_Fantastic.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emotional & Reaction Terms/Reviews_ExtracTerm_Good.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emotional & Reaction Terms/Reviews_ExtracTerm_Great.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emotional & Reaction Terms/Reviews_ExtracTerm_Hard.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emotional & Reaction Terms/Reviews_ExtracTerm_Hate.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emotional & Reaction Terms/Reviews_ExtracTerm_Helpful.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emotional & Reaction Terms/Reviews_ExtracTerm_Interesting.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emotional & Reaction Terms/Reviews_ExtracTerm_Like.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emotional & Reaction Terms/Reviews_ExtracTerm_Love.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emotional & Reaction Terms/Reviews_ExtracTerm_Nice.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emotional & Reaction Terms/Reviews_ExtracTerm_Poor.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emotional & Reaction Terms/Reviews_ExtracTerm_Recommend.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emotional & Reaction Terms/Reviews_ExtracTerm_Thank.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emotional & Reaction Terms/Reviews_ExtracTerm_Understand.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emotional & Reaction Terms/Reviews_ExtracTerm_Useful.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emotional & Reaction Terms/Reviews_ExtracTerm_Well.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emotional & Reaction Terms/Reviews_ExtracTerm_Wonderful.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M1 NLTK/Reviews_ExtracTerm_C_Sent_Assignment.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M1 NLTK/Reviews_ExtracTerm_C_Sent_Content.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M1 NLTK/Reviews_ExtracTerm_C_Sent_Course.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M1 NLTK/Reviews_ExtracTerm_C_Sent_Design.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M1 NLTK/Reviews_ExtracTerm_C_Sent_Exercise.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M1 NLTK/Reviews_ExtracTerm_C_Sent_Information.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M1 NLTK/Reviews_ExtracTerm_C_Sent_Instructor.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M1 NLTK/Reviews_ExtracTerm_C_Sent_Knowledge.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M1 NLTK/Reviews_ExtracTerm_C_Sent_Lecture.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M1 NLTK/Reviews_ExtracTerm_C_Sent_Lecturer.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M1 NLTK/Reviews_ExtracTerm_C_Sent_Lesson.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M1 NLTK/Reviews_ExtracTerm_C_Sent_Material.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M1 NLTK/Reviews_ExtracTerm_C_Sent_Method.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M1 NLTK/Reviews_ExtracTerm_C_Sent_Presentation.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M1 NLTK/Reviews_ExtracTerm_C_Sent_Professor.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M1 NLTK/Reviews_ExtracTerm_C_Sent_Quality.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M1 NLTK/Reviews_ExtracTerm_C_Sent_Question.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M1 NLTK/Reviews_ExtracTerm_C_Sent_Quizz.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M1 NLTK/Reviews_ExtracTerm_C_Sent_Slide.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M1 NLTK/Reviews_ExtracTerm_C_Sent_Speaker.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M1 NLTK/Reviews_ExtracTerm_C_Sent_Student.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M1 NLTK/Reviews_ExtracTerm_C_Sent_Teach.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M1 NLTK/Reviews_ExtracTerm_C_Sent_Teacher.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M1 NLTK/Reviews_ExtracTerm_C_Sent_Time.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M1 NLTK/Reviews_ExtracTerm_C_Sent_Topic.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M1 NLTK/Reviews_ExtracTerm_C_Sent_Video.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M2 Learn NB/Reviews_ExtracTerm_C_Sent_Assignment.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M2 Learn NB/Reviews_ExtracTerm_C_Sent_Content.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M2 Learn NB/Reviews_ExtracTerm_C_Sent_Course.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M2 Learn NB/Reviews_ExtracTerm_C_Sent_Design.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M2 Learn NB/Reviews_ExtracTerm_C_Sent_Exercise.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M2 Learn NB/Reviews_ExtracTerm_C_Sent_Information.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M2 Learn NB/Reviews_ExtracTerm_C_Sent_Instructor.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M2 Learn NB/Reviews_ExtracTerm_C_Sent_Knowledge.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M2 Learn NB/Reviews_ExtracTerm_C_Sent_Lecture.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M2 Learn NB/Reviews_ExtracTerm_C_Sent_Lecturer.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M2 Learn NB/Reviews_ExtracTerm_C_Sent_Lesson.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M2 Learn NB/Reviews_ExtracTerm_C_Sent_Material.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M2 Learn NB/Reviews_ExtracTerm_C_Sent_Method.html.
Failed to retrieve https://pageperso.lis-lab.fr/ismail.badache/Reviews_ExtracTerms%20HTML/Aspect%20Terms%20Sentiment%20M2%20Learn%20NB/Reviews_ExtracTerm_C_Sent_Presentation.html and no alternative available.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M2 Learn NB/Reviews_ExtracTerm_C_Sent_Professor.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M2 Learn NB/Reviews_ExtracTerm_C_Sent_Quality.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M2 Learn NB/Reviews_ExtracTerm_C_Sent_Question.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M2 Learn NB/Reviews_ExtracTerm_C_Sent_Quizz.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M2 Learn NB/Reviews_ExtracTerm_C_Sent_Slide.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M2 Learn NB/Reviews_ExtracTerm_C_Sent_Speaker.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M2 Learn NB/Reviews_ExtracTerm_C_Sent_Student.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M2 Learn NB/Reviews_ExtracTerm_C_Sent_Teach.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M2 Learn NB/Reviews_ExtracTerm_C_Sent_Teacher.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M2 Learn NB/Reviews_ExtracTerm_C_Sent_Time.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M2 Learn NB/Reviews_ExtracTerm_C_Sent_Topic.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment M2 Learn NB/Reviews_ExtracTerm_C_Sent_Video.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emoticones/Reviews_ExtracTerm_EmotHaha.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emoticones/Reviews_ExtracTerm_EmotLove.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emoticones/Reviews_ExtracTerm_EmotSad.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Emoticones/Reviews_ExtracTerm_EmotSmile.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M1 NLTK/Sent_Cont_Assignment.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M1 NLTK/Sent_Cont_Content.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M1 NLTK/Sent_Cont_Course.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M1 NLTK/Sent_Cont_Design.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M1 NLTK/Sent_Cont_Exercise.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M1 NLTK/Sent_Cont_Information.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M1 NLTK/Sent_Cont_Instructor.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M1 NLTK/Sent_Cont_Knowledge.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M1 NLTK/Sent_Cont_Lecture.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M1 NLTK/Sent_Cont_Lecturer.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M1 NLTK/Sent_Cont_Lesson.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M1 NLTK/Sent_Cont_Material.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M1 NLTK/Sent_Cont_Method.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M1 NLTK/Sent_Cont_Presentation.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M1 NLTK/Sent_Cont_Professor.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M1 NLTK/Sent_Cont_Quality.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M1 NLTK/Sent_Cont_Question.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M1 NLTK/Sent_Cont_Quizz.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M1 NLTK/Sent_Cont_Slide.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M1 NLTK/Sent_Cont_Speaker.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M1 NLTK/Sent_Cont_Student.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M1 NLTK/Sent_Cont_Teach.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M1 NLTK/Sent_Cont_Teacher.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M1 NLTK/Sent_Cont_Time.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M1 NLTK/Sent_Cont_Topic.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M1 NLTK/Sent_Cont_Video.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M2 Learn NB/Sent_Cont_Assignment.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M2 Learn NB/Sent_Cont_Content.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M2 Learn NB/Sent_Cont_Course.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M2 Learn NB/Sent_Cont_Design.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M2 Learn NB/Sent_Cont_Exercise.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M2 Learn NB/Sent_Cont_Information.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M2 Learn NB/Sent_Cont_Instructor.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M2 Learn NB/Sent_Cont_Knowledge.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M2 Learn NB/Sent_Cont_Lecture.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M2 Learn NB/Sent_Cont_Lecturer.html.
skipping download - already exists: /home/michael/.cache/lis-lab.fr/WelcomeCourseraDataset/Aspect Terms Sentiment_Cont M2 Learn NB/Sent_Cont_Lesson.html.

/tmp/ipykernel_415837/3371201340.py:21: UserWarning: Skipping Unsupported filetype: /home/michael/.cache/kagglehub/datasets/sabrisangjaya/udemy-course-review/versions/1/description.txt
  warnings.warn(f'Skipping Unsupported filetype: {file}')

saved UdemyCourseReview
downloading https://huggingface.co/datasets/chillies/course-review-multilabel-sentiment-analysis
downloaded to /home/michael/.cache/huggingface/datasets/chillies___course-review-multilabel-sentiment-analysis/default/0.0.0/ee899581a695c4a074b7450e57021bbb5fec1f7c
files: ['dataset_info.json', 'course-review-multilabel-sentiment-analysis-test.arrow', 'course-review-multilabel-sentiment-analysis-train.arrow']
saved ChilliesCoursereviews2024
all done

make obsidian links for documents (bash)

` ls -1 | sed 's:\(.*\).md:[[Datasets\/\1]]:'`

In [65]:
bigsumm = []

for k,v in SUMMARIEs.items():
    for tn, tbl in v.items():
        tbl["item"] = k
        tbl["tbl"] = tn
        bigsumm.append(tbl)

In [66]:
bigsumm = pd.concat(bigsumm, ignore_index=True)
bigsumm

,Column,data type,non-null values,non-null values %,unique values,Hist,example1,example2,item,tbl
0,review_id,int64,16562,100.00%,4000,![Histogram](img/Yhua219EduRABSA_ASQEDatasets2...,1369,545,Yhua219EduRABSA_ASQEDatasets2025,train
1,id,object,16562,100.00%,4000,![Histogram](img/Yhua219EduRABSA_ASQEDatasets2...,ASQE_1870,ASQE_846,Yhua219EduRABSA_ASQEDatasets2025,train
2,original_id,object,16562,100.00%,4000,![Histogram](img/Yhua219EduRABSA_ASQEDatasets2...,1_250_145_13533,2_8993_321,Yhua219EduRABSA_ASQEDatasets2025,train
3,text,object,16562,100.00%,3998,![Histogram](img/Yhua219EduRABSA_ASQEDatasets2...,Mrs. Chaney is such a sweet lady. The class ma...,Its tragic this is an antreq with SYDE 522 cau...,Yhua219EduRABSA_ASQEDatasets2025,train
4,task_type,object,16562,100.00%,1,![Histogram](img/Yhua219EduRABSA_ASQEDatasets2...,ASQE,ASQE,Yhua219EduRABSA_ASQEDatasets2025,train
...,...,...,...,...,...,...,...,...,...,...
119,Support Request,int64,821,100.00%,2,![Histogram](img/ChilliesCoursereviews2024_tes...,0,0,ChilliesCoursereviews2024,test
120,Community Interaction,float64,821,100.00%,2,![Histogram](img/ChilliesCoursereviews2024_tes...,0.0,0.0,ChilliesCoursereviews2024,test
121,Course Comparison,int64,821,100.00%,2,![Histogram](img/ChilliesCoursereviews2024_tes...,0,0,ChilliesCoursereviews2024,test
122,Related Course Suggestions,int64,821,100.00%,2,![Histogram](img/ChilliesCoursereviews2024_tes...,0,0,ChilliesCoursereviews2024,test
123,not_praise,int64,821,100.00%,2,![Histogram](img/ChilliesCoursereviews2024_tes...,0,0,ChilliesCoursereviews2024,test

In [67]:
bigsumm.columns = [ c.replace(" ","_").replace("-","_").replace("%","pct") for c in bigsumm.columns]

In [68]:
bigsumm

,Column,data_type,non_null_values,non_null_values_pct,unique_values,Hist,example1,example2,item,tbl
0,review_id,int64,16562,100.00%,4000,![Histogram](img/Yhua219EduRABSA_ASQEDatasets2...,1369,545,Yhua219EduRABSA_ASQEDatasets2025,train
1,id,object,16562,100.00%,4000,![Histogram](img/Yhua219EduRABSA_ASQEDatasets2...,ASQE_1870,ASQE_846,Yhua219EduRABSA_ASQEDatasets2025,train
2,original_id,object,16562,100.00%,4000,![Histogram](img/Yhua219EduRABSA_ASQEDatasets2...,1_250_145_13533,2_8993_321,Yhua219EduRABSA_ASQEDatasets2025,train
3,text,object,16562,100.00%,3998,![Histogram](img/Yhua219EduRABSA_ASQEDatasets2...,Mrs. Chaney is such a sweet lady. The class ma...,Its tragic this is an antreq with SYDE 522 cau...,Yhua219EduRABSA_ASQEDatasets2025,train
4,task_type,object,16562,100.00%,1,![Histogram](img/Yhua219EduRABSA_ASQEDatasets2...,ASQE,ASQE,Yhua219EduRABSA_ASQEDatasets2025,train
...,...,...,...,...,...,...,...,...,...,...
119,Support Request,int64,821,100.00%,2,![Histogram](img/ChilliesCoursereviews2024_tes...,0,0,ChilliesCoursereviews2024,test
120,Community Interaction,float64,821,100.00%,2,![Histogram](img/ChilliesCoursereviews2024_tes...,0.0,0.0,ChilliesCoursereviews2024,test
121,Course Comparison,int64,821,100.00%,2,![Histogram](img/ChilliesCoursereviews2024_tes...,0,0,ChilliesCoursereviews2024,test
122,Related Course Suggestions,int64,821,100.00%,2,![Histogram](img/ChilliesCoursereviews2024_tes...,0,0,ChilliesCoursereviews2024,test
123,not_praise,int64,821,100.00%,2,![Histogram](img/ChilliesCoursereviews2024_tes...,0,0,ChilliesCoursereviews2024,test

In [75]:
bigsumm = bigsumm[['item', 'tbl', 'Column', 'data_type', 'non_null_values', 'non_null_values_pct',
       'unique_values', 'Hist', 'example1', 'example2', ]]

In [77]:
bigsumm.item.nunique()

6

In [76]:
bigsumm.to_csv(outputs_root + "/all_summaries.csv")

In [ ]:
from duckdb import sql as sqldf
from plotly import express as px

In [ ]:
q = """ --
select item, tbl, 
max(non_null_values) as non_null_values 
-- take column with max non-null values for every table - upper bound of how much data it has
from bigsumm

group by item , tbl
order by non_null_values desc
"""

wat = sqldf(q).df()

wat

In [ ]:
px.bar(wat, x="item", y="non_null_values", color="tbl", 
           title="Average non-null values per table and item",
            height = 600, labels=False) 
#, log_y=True)

In [ ]:
wat.keys()

In [ ]:
summary(wat)

## Play around with generation

In [ ]:
PROJECT_NAME = "synthetic-dolly" # @param {type:"string"}
DATASET_NAME = "databricks/databricks-dolly-15k" # @param {type:"string"}
MAX_ROWS = 1000 # @param {type:"integer"}
UPSAMPLE = 1 # @param {type:"integer"}

In [ ]:
def load_and_clean_dataset(dataset_name, n_rows):
    """ Load and clean a dataset from HuggingFace. """
    dataset = load_dataset(dataset_name, split='train').select(range(n_rows))
    df = pd.DataFrame(dataset)
    df = df.applymap(lambda x: x.replace('\n', ' ').replace('\r', ' ').encode('ascii', 'ignore').decode('ascii'))
    return df

df = load_and_clean_dataset(DATASET_NAME, MAX_ROWS)

In [ ]:
df